In [8]:
import numpy as np
print(np.__version__)

1.24.3


In [11]:
a = np.array([1, 2, 5, 10])
print(a)

print(type(a))

print(a.size)
print(a.shape)

[ 1  2  5 10]
<class 'numpy.ndarray'>
4
(4,)


In [14]:
print(a.nbytes)

print(a.ndim)

print(a.dtype)

16
1
int32


In [48]:
x = np.array([1, 2, 3, 6, 12])
y = np.array([7, 8, 15, 10, 26])
z = np.array([10, 5, 12, 11, 13])



print(6*8*5)


print(f"x= {x} and y= {y}")



print(x+y)
print(y-x)
print(x*y)

print(x)

240
x= [ 1  2  3  6 12] and y= [ 7  8 15 10 26]
[ 8 10 18 16 38]
[ 6  6 12  4 14]
[  7  16  45  60 312]
[ 1  2  3  6 12]


In [33]:
print(z.nbytes)
print(z.sum())


20
440


# practise sets

In [3]:
import numpy as np
b = np.array([1,2,3,4,5,6,7,8,9])
print(b)

print(b.sum())

print(b.min())

print(b.max())

print(b.mean())

print(b.std())

print(b[2])

print(b[1:4])

[1 2 3 4 5 6 7 8 9]
45
1
9
5.0
2.581988897471611
3
[2 3 4]
