In [1]:
import numpy as np
print(np.__version__)
a = np.array([1, 2, 3, 4, 5])
print(a)


1.24.3
[1 2 3 4 5]


In [2]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(b.shape)
print(b.size)

(2, 3)
6


In [9]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(x.shape)
print(x.size)

(3, 3)
9


In [20]:
print(x[1][2])
print(x[2][2])

6
9


In [21]:
print(x.sum())
print(x.sum(axis=0))     #vertical line sum
print(x.sum(axis=1))     #horizontal line sum

45
[12 15 18]
[ 6 15 24]


In [29]:
c = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(c)

print(c[1,:])       #for particular row

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


In [30]:
print(c[:,1])        #for particular column

[2 5 8]


In [32]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [34]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [35]:
x = np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b = np.array([10, 11, 12, 14, 16])
print(a)
print(b)

print(a[1:7:2])
print(a[1:7])
print(a[::])

[1 2 3 4 5 6 7 8]
[10 11 12 14 16]
[2 4 6]
[2 3 4 5 6 7]
[1 2 3 4 5 6 7 8]


In [51]:
c = np.hstack([a,b])
print(c)


[ 1  2  3  4  5  6  7  8 10 11 12 14 16]


# dictionary






In [63]:
stud={
    'name':'ram',
    'age':22,
    'mark':77.5,
    'address':['pokhara','kathmandu']
    
}
print(stud)

{'name': 'ram', 'age': 22, 'mark': 77.5, 'address': ['pokhara', 'kathmandu']}


In [64]:
print(stud.keys())

dict_keys(['name', 'age', 'mark', 'address'])


In [65]:
print(stud.values())

dict_values(['ram', 22, 77.5, ['pokhara', 'kathmandu']])
